name: Build and Publish Docker Image
on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build docker image
        run: chmod +x build.sh && ./build.sh